# Generated by Django 6.0.1 on 2026-02-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('guest_id', models.TextField()),
                ('room', models.TextField()),
                ('my_message', models.TextField()),
                ('my_photo', models.ImageField(blank=True, null=True, upload_to='chat/photos/%Y/%m/%d/')),
                ('my_file', models.FileField(blank=True, null=True, upload_to='chat/files/%Y/%m/%d/')),
                ('my_voice_message', models.FileField(blank=True, null=True, upload_to='chat/voice/%Y/%m/%d/')),
                ('my_timestamp', models.DateTimeField(auto_now_add=True)),
                ('guest_message', models.TextField()),
                ('guest_photo', models.ImageField(blank=True, null=True, upload_to='chat/photos/%Y/%m/%d/')),
                ('guest_file', models.FileField(blank=True, null=True, upload_to='chat/files/%Y/%m/%d/')),
                ('guest_voice_message', models.FileField(blank=True, null=True, upload_to='chat/voice/%Y/%m/%d/')),
                ('guest_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('guest_id', models.TextField()),
                ('room', models.TextField()),
                ('count', models.TextField()),
                ('groups', models.TextField()),
            ],
        ),
    ]
