# Generated by Django 6.0.1 on 2026-02-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='room',
            field=models.TextField(unique=True),
        ),
    ]
