# Generated by Django 6.0.1 on 2026-02-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_userdata_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='room',
            field=models.TextField(),
        ),
    ]
