# Generated by Django 6.0.1 on 2026-01-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=225, unique=True, verbose_name='Логин пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail пользователя')),
                ('number', models.TextField()),
                ('status', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
