# Generated by Django 6.0.1 on 2026-01-22 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=225, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.TextField()),
                ('status', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_message', models.TextField()),
                ('user_message', models.TextField()),
                ('room', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chat/photos/%Y/%m/%d/')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/files/%Y/%m/%d/')),
                ('voice_message', models.FileField(blank=True, null=True, upload_to='chat/voice/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='sign_up.models')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacs', models.TextField()),
                ('rooms', models.TextField()),
                ('groups', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sign_up.models')),
            ],
        ),
    ]
