# Generated by Django 6.0.1 on 2026-01-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='contacs',
            new_name='user_contacs',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.TextField(),
        ),
    ]
