# Generated by Django 6.0.1 on 2026-01-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0002_rename_contacs_userdata_user_contacs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
