# Generated by Django 6.0.1 on 2026-01-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0003_remove_message_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
